### ISSUE TITLE
enable TestMiningBenchmark in `main`

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#10313]
`eth/stagedsync/stage_mining_create_block.go` usin `state.NewPlainStateReader` - need switch to E3 primitives
and this test is stuck - need investigate why and fix
probably it blocking https://github.com/ledgerwatch/erigon/pull/10940
prev attempt: https://github.com/ledgerwatch/erigon/pull/10559

**Comment by AskAlexSharov** [comment]
@Giulio2002 @awskii - maybe this is unit-test for Unwind on membatch.

**Comment by awskii** [comment]
I just stop skipping it and test fails by timeout, no good peers found and nothing happens, have to dig it.

**Comment by awskii** [comment]
`pool.go:711: DBUG[06-24|16:56:50.604] [txpool] Waiting for block               expecting=1 lastSeen=0 txRequested=50 pending=5000 baseFee=0 queued=0`
So pool is filled with 5k txs. 

test stucks here `p.lastSeenCond.Wait()`
`StateChangesClient.StateChanges` - something is wrong here since this should have return a state change
