### ISSUE TITLE
Investigate why bor-mainnet ComputeCommitment touching much Level0 state files

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11304]
it's not about speed - but just about amount of requests there. 
- what do we read from Level0 of commitment
- what do we read from Level0 of storage

**Comment by Giulio2002** [comment]
commitment - I guess all of the unnecessary unfoldig... lots of random writes in possibly untouched entries

**Comment by AskAlexSharov** [comment]
dYes, question is - why “unfold” need much of old-and-never-updated (Level0) data.

**Comment by awskii** [comment]
Since we have packed accounts and storage into one trie - they are all sharing prefixes. All storage writes made within L0 file could be triggered due to updates on those prefixes. If lots of updates happening on storage addresses active at L0, we read alot of old branches along with recent storages.

During trie unfolding reduce i spotted that caching of storage hashes on top of what we have already is almost useless since we already do read minimum needed from storage domain.
