### ISSUE TITLE
`stage_bor_heimdall` commit partial progress if external `rwtx` is nil

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#11904]
see example in another stages: `useExternalTx := txc.Tx != nil`

**Comment by stevemilk** [comment]
Hi Sir, I want help fix this issue but have a question:
In `stage_exec` , external rwtx is defined as from kv.chainDB. It can be nil if noCommit==false, and that's why we use `useExternalTx := txc.Tx != nil`. 
However, in`stageBorHeimdall`,external rwtx will definitely be created as a non-nil value by db.update() if no error thrown. Is this true? if true, no need to fix this.

**Comment by AskAlexSharov** [comment]
There are several places where stages are  called. Some pass external rwtx, some are not. 

“integration” usually doesn’t.

 kv.RwTx and kv.RwDB are 2 different objects.

**Comment by stevemilk** [comment]
draft a pr #12097 to enable stage_bor_heimdall to commit partial progress, is this as expected?
