### ISSUE TITLE
Don't re-open frozen segments

### ISSUE THREAD

**Issue by mh0lt** [erigontech/erigon#12299]
At the moment 

```
func (s *RoSnapshots) rebuildSegments(fileNames []string, open bool, optimistic bool) error
```

Reopens all segments even if they are already open and frozen, hence will not change due to extract and merge operations.

This is inefficient as it closes and open files which costs os resources and potentially disturbs file caching.

**Comment by stevemilk** [comment]
During snapshotsync, part of downloaded files can be frozen, but we do need to reopen in case files are partially downloaded. So I think question goes back to how to verify the integrity of files. 
It occurred to me  that we can add a flag: `downloadComplete` and set it to be true after snapshotSync complete downloading so that subsequent `reopen` will not open those opened fils. The only flaw is it has to wait all files complete downloading.  
I draft a PR and you can check if it's viable #12307. 
 
btw, I prepared #12245 for this kind of issue too, need to pass the integration tests first though(i'm following up).  This intends to maintain commitment files for downloaded files.  
hope to get your advice, thank you :)

**Comment by AskAlexSharov** [comment]
done by https://github.com/erigontech/erigon/pull/12332
