### ISSUE TITLE
v3.0.0-alpha5 Known issue

### ISSUE THREAD

**Issue by journeytosilius** [erigontech/erigon#12880]
> Known problems
> There is still some instability in the RPC

What does some instability in the RPC means exactly ?

**Comment by AskAlexSharov** [comment]
please use `main` git branch - we fixed rpc there. 
list of fixes: https://github.com/erigontech/erigon/milestone/5?closed=1

**Comment by journeytosilius** [comment]
but which release to use for erigon 3 ? currently I'm using 

```
* (HEAD detached at v3.0.0-alpha5)
  main
```
And it synced ok, but ws RPC is very slow ?

**Comment by AskAlexSharov** [comment]
@journeytosilius 
- use `main`
- `before` - when?
- Erigon3 doesn't store receipts/logs for now (Erigon2 did). Because re-exec of 1 historical txn is cheaper in E3 than in E2. We still adding some optimizations to RPC - to make re-exec of 1 txn cheaper. If after our work done - perf of fetching receipts will still be not enough: we will introduce "optional persistence" of rpc logs.

**Comment by journeytosilius** [comment]
@AskAlexSharov  this was just me first testing v3.0.0-alpha5
Then I realized that this was the problem and I made another issue : https://github.com/erigontech/erigon/issues/12892#issuecomment-2508984227, 
I forgot that Erigon 3 is still alpha, nevermind :)
