### ISSUE TITLE
eth_getBlockReceipts erigon v3 takes much time

### ISSUE THREAD

**Issue by fridary** [erigontech/erigon#13119]
**Erigon version:** 3.00.0-alpha5-78f3647d
**OS & Version:** Debian 6.1.119-1 (2024-11-22) x86_64, CPU E5-2695 v4, 36 cores, 192 Gb RAM
**Disk:** NVMe HPE MT006400KWHAE 6.4 Tb
**Erigon Command (with flags/config):** /root/erigon/build/bin/erigon --datadir=/disk_nvme/erigon --ws --http.api=eth,erigon,engine,web3,net,debug,trace,txpool --authrpc.jwtsecret=/root/erigon/jwtsecret --torrent.download.rate=512mb --rpc.batch.limit=5000

Erigon successfully installed in 3 days archive node and took 1.8Tb disk space. Everything great, but eth_getBlockReceipts requests take more time than I do the same request somewhere to public node.

```python
    testnet = 'http://127.0.0.1:8545'
    #testnet = 'https://eth-pokt.nodies.app'

    w3 = Web3(Web3.HTTPProvider(f"{testnet}"))
    block_number = 11908500
    print(f"testnet={testnet}, block_number={block_number}")

    start_time = time.time()
    block = requests.post(testnet, json={"method":"eth_getBlockByNumber","params":[hex(block_number),True],"id":1,"jsonrpc":"2.0"}, headers={"Content-Type": "application/json"}).json()['result']
    print('eth_getBlockByNumber:', f"{(time.time() - start_time):.3f}s")

    start_time = time.time()
    block = requests.post(testnet, json={"method":"eth_getBlockReceipts","params":[hex(block_number)],"id":2,"jsonrpc":"2.0"}, headers={"Content-Type": "application/json"}).json()['result']
    print('eth_getBlockReceipts:', len(block), f"{(time.time() - start_time):.3f}s")

    start_time = time.time()
    block = requests.post(testnet, json={"method":"debug_traceBlockByNumber","params":[hex(block_number),{"tracer":"callTracer"}],"id":3,"jsonrpc":"2.0"}, headers={"Content-Type": "application/json"}).json()['result']
    print('debug_traceBlockByNumber:', f"{(time.time() - start_time):.3f}s")
```
result:
```
testnet=http://127.0.0.1:8545, block_number=11908500
eth_getBlockByNumber: 0.013s
eth_getBlockReceipts: 176 1.625s
debug_traceBlockByNumber: 0.076s
```
result on public:
```
testnet=https://eth-pokt.nodies.app, block_number=11908500
eth_getBlockByNumber: 0.228s
eth_getBlockReceipts: 176 0.245s
debug_traceBlockByNumber: 1.507s
```

We can see eth_getBlockReceipts on local erigon is in ~6 times slower than public node.
Any ideas how to fix?

**Comment by AskAlexSharov** [comment]
Hi. 
1. Erigon3 currently doesn't store receipts (any), even on archive mode. It re-executing txs to get logs (with small LRU cache of receipts). But Erigon3 allows re-exec txs faster than E2 (because of per-transaction history granularity) - without re-executin whole block. Means `eth_getLogs` (with good filters) may be good-enough in speed (even if we do re-exec txs), or `eth_getTransactionReceipt`.
2. We may introduce optional "persistent logs/receipts" feature in future (if users will need it). 
3. Currently we trying to remove bottlenecks in historical re-exec: for example we improved ~25% here https://github.com/erigontech/erigon/pull/12970 (require re-sync to see effect, and bottleneck is still same). Current bottleneck is: "size of history index - `.efi` file). I working on it here: https://github.com/erigontech/erigon/issues/12852
4. In `eth_getBlockReceipts` it's also possible to exec txs in-parallel. It will speedup individual request - but may reduce a bit overall throughput. So, i would be careful here. 
@fridary What do you think?

**Comment by AskAlexSharov** [comment]
only thing i don't understand: `debug_traceBlockByNumber: 0.076s` why it's much faster than receipts gen (in-theory it does the same thing). Let me check.

**Comment by AskAlexSharov** [comment]
ah, it's because `eth_getBlockReceipts` did warm-up PageCache for `debug_traceBlockByNumber`. See same speed on my machine: ~1.1sec of cold call, ~0.2sec for warm call.

**Comment by fridary** [comment]
@AskAlexSharov I need to query `eth_getBlockReceipts` only once for indexing blockchain to database, no need to query again and get warm call. So, warm calls are only when I do second request for the same block?

**Comment by AskAlexSharov** [comment]
Neighbor blocks are likely will also warmup each-other (their data often co-located).
