### ISSUE TITLE
dl: wrong `complete` calc when node synced

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#9940]
Existing node (has all files) already executing blocks - but still see much debug logs from downloader:
```
[DBUG] [04-15|08:53:03.543] [snapshots] webseed peers                file=history/v1-storage.2432-2464.v
[DBUG] [04-15|08:53:03.543] [snapshots] bittorrent peers             file=history/v1-storage.2432-2464.v erigon: 2.60.1-dev-c3824cf5=0B/s erigon: 2.60.1-dev-c3824cf5=0B/s
[DBUG] [04-15|08:53:03.544] [snapshots] progress                     file=idx/v1-accounts.2432-2464.ef progress=100.00% peers=0 webseeds=0
```

Reason is:
```
		var torrentComplete bool
		torrentName := t.Name()

		if _, ok := downloading[torrentName]; ok {
			torrentComplete = t.Complete.Bool()
		}
``` 
file - can be completed - even if we not downloaded it (start erigon on downloaded files).

**Comment by AskAlexSharov** [comment]
Probably this code `if downloading && t.Complete.Bool() {` in `mainLoop` is also buggy by same reason.

**Comment by AskAlexSharov** [comment]
Maybe let's remove `d.downloading` ?

**Comment by mh0lt** [comment]
We can do this.  It will just re-introduce premature downloader completion.

The underlying issue here is that Torrent.Complete is itself unreliable.

I think a better way of doing this is to examine. Torrent._completedPieces which is the actual source of truth and doesn't depend on the torrent code remembering to update Complete - which I don't think it always does correctly.

Lets wee what bugs emerge from re-testing post this change.
